/*
 * This source file was generated by the Gradle 'init' task
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestOQBuilder {


    // Test that all valid combinations of purple spheres create valid boards 
    @Test void testAllOQBoardsExist() {
        int numBoards = Combinatorics.nCr(25, 4);
        
        BoardBuilderOQ builder = new BoardBuilderOQ();
        Board[] allBoards = new Board[numBoards];

        for(int i = 0; i < numBoards; i++){
            allBoards[i] = builder.build(i);
        }

        // Check all 12650 boards exist without duplicates
        int numBoardsTested = 
            allBoards.stream()
            .map(Arrays::toString()
            .collect(Collectors.toSet())
            .size();

        // If they are not equal, then duplicate boards were removed when creating sets.
        assertEquals(numBoards, numBoardsTested);

    }


}
