/*
 * This source file was generated by the Gradle 'init' task
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {


    // Test that all valid combinations of purple spheres create valid boards 
    @Test void testAllOQBoardStatesExist() {
        int numBoards = Combinatorics.nCr(25, 4);
        
        BoardBuilderOQ builder = new BoardBuilderOQ();
        Board[] allBoards = new Board[numBoards];

        for(int i = 0; i < numBoards; i++){
            allBoards[i] = builder.build(i);
        }

        // Check all boards are valid, and without duplicates
        // TODO


    }
}
