/*
 * This source file was generated by the Gradle 'init' task
 */
package ouroquest;

import java.util.Arrays;
import java.util.stream.Collectors;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import game.board.Tile;
import game.board.Board;
import game.board.BoardBuilderOQ;

import math.Combinatorics;

import game.sphere.Sphere;
import game.sphere.SphereType;



class TestOQBuilder {


    // Test that all valid combinations of purple spheres create valid boards 
    @Test void testAllOQBoardsExist() {
        int numBoards = Combinatorics.nCr(25, 4);
        
        BoardBuilderOQ builder = new BoardBuilderOQ();
        int[][][] allBoards = new int[numBoards][5][5];

        for(int i = 0; i < numBoards; i++){
            allBoards[i] = builder.buildHeat(i);
        }

        // Check all 12650 boards exist without duplicates
        int numBoardsTested = 
            Arrays.stream(allBoards)
            .map(Arrays::deepToString)
            .collect(Collectors.toSet())
            .size();

        // If they are not equal, then duplicate boards were removed when creating sets.
        assertEquals(numBoards, numBoardsTested);

    }

    @Test void testAllOQBoardsValid() {
        int numBoards = Combinatorics.nCr(25, 4);

        BoardBuilderOQ builder = new BoardBuilderOQ();
        Board[] allBoards = new Board[numBoards];

        for(int i = 0; i < numBoards; i++){
            allBoards[i] = builder.build(i);
        }


        int purpleCount = 0;
        int[][] purples = new int[4][2]; // reusable

        for(int i = 0; i < numBoards; i++){
            Tile[][] tiles = allBoards[i].getTiles();
            
            for(int j = 0; j < 5; j++){
                for(int k = 0; k < 5; k++){
                    if(tiles[j][k].getSphere().getType() == SphereType.PURPLE){
                        purples[purpleCount][0] = j;    // just store index pairs to avoid headaches in locating purples
                        purples[purpleCount][1] = k; 
                        purpleCount++;
                    }
                }
            }

            boolean fail = false; // for fear of asserting too many times, will assert once instead of 25x

            // knowing the positions of purples , validate every other element of this board
            for(int j = 0; j < 5; j++){
                for(int k = 0; k < 5; k++){
                    if(tiles[j][k].getSphere().getType() == SphereType.PURPLE)  // a quick check to avoid headaches 
                        continue;

                    int heat = 0;

                    // 3x3 grid around current index
                    for(int j2 = j-1; j2 <= j+1; j2++){
                        for(int k2 = k-1; k2 <= k+1; k2++){
                            if(j2 < 0 || j2 > 4 || k2 < 0 || k2 > 4 || (j2 == j && k2 == k)){
                                continue;
                            }else{
                                for(int m  = 0; m < 4; m++){
                                    if(j2 == purples[m][0] && k2 == purples[m][1])
                                        heat++;
                                }
                            }
                        }
                    }

                    SphereType type = null;
                    switch(heat){
                        case 0:
                            type = SphereType.BLUE;
                            break;
                        case 1:
                            type = SphereType.TEAL;
                            break;
                        case 2:
                            type = SphereType.GREEN;
                            break;
                        case 3:
                            type = SphereType.YELLOW;
                            break;
                        case 4:
                            type = SphereType.ORANGE;
                            break;
                        default:
                            throw new IllegalStateException();
                    }


                    if(tiles[j][k].getSphere().getType() != type)
                        fail = true;

                }
            }


            assertFalse(fail);
            purpleCount = 0;

        }


    }

}
